Dir['tasks/**/*.rake'].sort.each { |rakefile| load rakefile }

task :default do
  puts 'This is an example rake task.'
end

task :site => [ :site_html, :site_js, :site_css ]

task :site_html do
  sh 'nanoc', 'co'
end

task :site_js do
  mkdir_p 'output/js'
  cp "../dist/jshoulda.js", 'output/js'
  cp "../test/assets/jsunittest.js", 'output/js'
  cp "js/editable.js", 'output/js'
end

task :site_css => [ 'output/css/unittest.css', 'output/css/blackboard.css' ]

file 'output/css/unittest.css' => 'css/unittest.css' do
  mkdir_p "output/css"
  cp "css/unittest.css", "output/css"  
end

file 'output/css/blackboard.css' => 'css/blackboard.css' do
  mkdir_p "output/css"
  cp "css/blackboard.css", "output/css"  
end

